// generated by update-media.command - do not edit by hand
window.MEDIA = {
 videos: [
  "videos/24fps.mp4",
  "videos/Eating glue with outline #3D #Blender # 3danimation #blenderanimation #blender3D.mp4",
  "videos/SILKSONG IN A FEW HOURS  #animation #silksong #hollowknight #hollowknightsilksong #3danimation.mp4",
  "videos/Stealing the silksong release date from team cherry's office ft@Brickatick.mp4",
  "videos/The peashooter dance  #blender3danimation #3d #animation #plantsvszombies #pvz #pvz2 #3dnimation.mp4",
  "videos/The quest for cereal #3D #animation #blender3danimation #blender #3Danimation #donut #doughnut.mp4",
  "videos/Totally real callout to Miyu Tells Tales.mp4",
  "videos/Untitled video   Made with Clipchamp.mp4",
  "videos/You decide what this 3D model does #3danimation  #animation #blender #blender3d.mp4",
 ],
 drawings: [
  "drawings/840133648_17901999273669519_1235432873108206356_n.webp",
  "drawings/840713921_17901834123669519_7898164230115950049_n.webp",
  "drawings/837494572_17901833904669519_3109836765694760492_n.webp",
  "drawings/750903835_17886033558669519_415061031154007010_n.webp",
  "drawings/donut_main_oc_2_by_ddonut12_dmo7zim.png",
  "drawings/donut_main_oc_1_by_ddonut12_dmo7z7a.png",
 ]
};
